language: go

go:
  - 1.7
  - 1.6
  - master

install:
  - go get github.com/kardianos/govendor

before_script:
  - govendor sync

script:
  - bash ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
